# Generated by Django 5.0.4 on 2024-05-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
