# Generated by Django 5.0.4 on 2024-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_userregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
