# Generated by Django 5.0.4 on 2024-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_image', models.ImageField(blank=True, null=True, upload_to='podcast_images/')),
                ('full_name', models.CharField(blank=True, max_length=240, null=True)),
                ('urls', models.JSONField()),
                ('time_stamp', models.CharField(blank=True, max_length=240, null=True)),
                ('podcast_des', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
