# Generated by Django 5.0.4 on 2024-05-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='urls',
        ),
        migrations.AddField(
            model_name='podcast',
            name='apple_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='google_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='spotify_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='youtube_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
