# Generated by Django 5.0.4 on 2024-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_podcast_apple_url_alter_podcast_google_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=240, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
