# Generated by Django 5.0.4 on 2024-05-02 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_bookrandall'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrandall',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
