# Generated by Django 5.0.4 on 2024-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_bookrandall_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('thumbnails', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
